[application]
name = "MorBlogger"
default_platform = "android"
asset_dir = "assets"
out_dir = "dist"

[bundle]
identifier = "com.moribund.morblogger"
publisher = "Moribund"

[web.app]
title = "MorBlogger"
