#!/usr/bin/env bash
# Concatenate modular stylesheets into src/editor_ui.css.
# Run from repo root: ./build_css.sh
set -euo pipefail

SRC_DIR="src/styles"
OUT="src/editor_ui.css"

if [ ! -d "$SRC_DIR" ]; then
  echo "error: $SRC_DIR not found" >&2
  exit 1
fi

{
  echo "/* AUTO-GENERATED by build_css.sh from src/styles/*.css"
  echo "   Do NOT edit this file by hand. Edit the modular sources and re-run the script. */"
  echo ""
  # Sort by filename so the numeric prefix controls cascade order.
  for f in $(find "$SRC_DIR" -maxdepth 1 -name '*.css' | LC_ALL=C sort); do
    echo ""
    echo "/* ============================================================"
    echo "   $(basename "$f")"
    echo "   ============================================================ */"
    cat "$f"
    echo ""
  done
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines from $(find "$SRC_DIR" -maxdepth 1 -name '*.css' | wc -l) sources)"
