#!/usr/bin/env bash
# Concatenate modular stylesheets into src/editor_ui.css.
# Can be run from any directory.
set -euo pipefail

# 1. Dynamically find the project root
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( dirname "$SCRIPT_DIR" )"

# 2. Use absolute paths based on the project root
SRC_DIR="$PROJECT_ROOT/src/editor_styles"
OUT="$PROJECT_ROOT/src/editor_ui.css"

if [ ! -d "$SRC_DIR" ]; then
    echo "error: $SRC_DIR not found" >&2
    exit 1
fi

{
    echo "/* AUTO-GENERATED by build_editor_styles.sh from src/editor_styles/*.css"
    echo "   Do NOT edit this file by hand. Edit the modular sources and re-run the script. */"
    echo ""
    # Sort by filename so the numeric prefix controls cascade order.
    for f in $(find "$SRC_DIR" -maxdepth 1 -name '*.css' | LC_ALL=C sort); do
        echo ""
        echo "/* ============================================================"
        echo "   $(basename "$f")"
        echo "   ============================================================ */"
        cat "$f"
        echo ""
    done
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines from $(find "$SRC_DIR" -maxdepth 1 -name '*.css' | wc -l) sources)"