[application]
name = "MorBlogger Theme Editor"
asset_dir = "assets"

[web.app]
title = "MorBlogger Theme Editor"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = []

[web.resource.dev]
style = []

[bundle]
identifier = "com.moribundinstitute.morblogger-theme-editor"
publisher = "Moribund Institute"
icon = [
    "assets/icon.png",
]
category = "DeveloperTool"
short_description = "A visual Blogger theme editor."
long_description = "MorBlogger Theme Editor is a Dioxus desktop app for visually building, previewing, and exporting Blogger themes."

[watcher]
ignore = [
    "editor_prefs.toml",
    "layout_prefs.toml",
    "*.txt",
    "*.md",
    "sys"
]
